var annotated_dup =
[
    [ "cen", "namespacecen.html", [
      [ "gl", "namespacecen_1_1gl.html", [
        [ "basic_context", "classcen_1_1gl_1_1basic__context.html", "classcen_1_1gl_1_1basic__context" ]
      ] ],
      [ "hint", "namespacecen_1_1hint.html", [
        [ "android", "namespacecen_1_1hint_1_1android.html", [
          [ "block_on_pause", "structcen_1_1hint_1_1android_1_1block__on__pause.html", null ],
          [ "trap_back_button", "structcen_1_1hint_1_1android_1_1trap__back__button.html", null ],
          [ "apk_expansion_main_file_version", "structcen_1_1hint_1_1android_1_1apk__expansion__main__file__version.html", null ],
          [ "apk_expansion_patch_file_version", "structcen_1_1hint_1_1android_1_1apk__expansion__patch__file__version.html", null ],
          [ "pause_background_audio", "structcen_1_1hint_1_1android_1_1pause__background__audio.html", null ]
        ] ],
        [ "appletv", "namespacecen_1_1hint_1_1appletv.html", [
          [ "controller_ui_events", "structcen_1_1hint_1_1appletv_1_1controller__ui__events.html", null ],
          [ "remote_allow_rotation", "structcen_1_1hint_1_1appletv_1_1remote__allow__rotation.html", null ]
        ] ],
        [ "controller", "namespacecen_1_1hint_1_1controller.html", [
          [ "use_button_labels", "structcen_1_1hint_1_1controller_1_1use__button__labels.html", null ],
          [ "type", "structcen_1_1hint_1_1controller_1_1type.html", null ],
          [ "config", "structcen_1_1hint_1_1controller_1_1config.html", null ],
          [ "config_file", "structcen_1_1hint_1_1controller_1_1config__file.html", null ],
          [ "ignore_devices", "structcen_1_1hint_1_1controller_1_1ignore__devices.html", null ],
          [ "ignore_devices_except", "structcen_1_1hint_1_1controller_1_1ignore__devices__except.html", null ]
        ] ],
        [ "d3d", "namespacecen_1_1hint_1_1d3d.html", [
          [ "v11_debug", "structcen_1_1hint_1_1d3d_1_1v11__debug.html", null ],
          [ "thread_safe", "structcen_1_1hint_1_1d3d_1_1thread__safe.html", null ]
        ] ],
        [ "emscripten", "namespacecen_1_1hint_1_1emscripten.html", [
          [ "keyboard_element", "structcen_1_1hint_1_1emscripten_1_1keyboard__element.html", null ],
          [ "asyncify", "structcen_1_1hint_1_1emscripten_1_1asyncify.html", null ]
        ] ],
        [ "joystick", "namespacecen_1_1hint_1_1joystick.html", [
          [ "allow_background_events", "structcen_1_1hint_1_1joystick_1_1allow__background__events.html", null ],
          [ "use_hidapi", "structcen_1_1hint_1_1joystick_1_1use__hidapi.html", null ],
          [ "use_hidapi_ps4", "structcen_1_1hint_1_1joystick_1_1use__hidapi__ps4.html", null ],
          [ "use_hidapi_ps4_rumble", "structcen_1_1hint_1_1joystick_1_1use__hidapi__ps4__rumble.html", null ],
          [ "use_hidapi_steam", "structcen_1_1hint_1_1joystick_1_1use__hidapi__steam.html", null ],
          [ "use_hidapi_switch", "structcen_1_1hint_1_1joystick_1_1use__hidapi__switch.html", null ],
          [ "use_hidapi_xbox", "structcen_1_1hint_1_1joystick_1_1use__hidapi__xbox.html", null ],
          [ "use_hidapi_game_cube", "structcen_1_1hint_1_1joystick_1_1use__hidapi__game__cube.html", null ],
          [ "use_hidapi_ps5", "structcen_1_1hint_1_1joystick_1_1use__hidapi__ps5.html", null ],
          [ "use_raw_input", "structcen_1_1hint_1_1joystick_1_1use__raw__input.html", null ],
          [ "rawinput_correlate_xinput", "structcen_1_1hint_1_1joystick_1_1rawinput__correlate__xinput.html", null ],
          [ "linux_use_deadzones", "structcen_1_1hint_1_1joystick_1_1linux__use__deadzones.html", null ]
        ] ],
        [ "mac", "namespacecen_1_1hint_1_1mac.html", [
          [ "fullscreen_spaces", "structcen_1_1hint_1_1mac_1_1fullscreen__spaces.html", null ],
          [ "background_app", "structcen_1_1hint_1_1mac_1_1background__app.html", null ],
          [ "ctrl_click_emulate_right_click", "structcen_1_1hint_1_1mac_1_1ctrl__click__emulate__right__click.html", null ]
        ] ],
        [ "mouse", "namespacecen_1_1hint_1_1mouse.html", [
          [ "focus_clickthrough", "structcen_1_1hint_1_1mouse_1_1focus__clickthrough.html", null ],
          [ "relative_mode_warp", "structcen_1_1hint_1_1mouse_1_1relative__mode__warp.html", null ],
          [ "double_click_time", "structcen_1_1hint_1_1mouse_1_1double__click__time.html", null ],
          [ "double_click_radius", "structcen_1_1hint_1_1mouse_1_1double__click__radius.html", null ],
          [ "normal_speed_scale", "structcen_1_1hint_1_1mouse_1_1normal__speed__scale.html", null ],
          [ "relative_speed_scale", "structcen_1_1hint_1_1mouse_1_1relative__speed__scale.html", null ],
          [ "relative_scaling", "structcen_1_1hint_1_1mouse_1_1relative__scaling.html", null ]
        ] ],
        [ "qtwayland", "namespacecen_1_1hint_1_1qtwayland.html", [
          [ "content_orientation", "structcen_1_1hint_1_1qtwayland_1_1content__orientation.html", null ],
          [ "window_flags", "structcen_1_1hint_1_1qtwayland_1_1window__flags.html", null ]
        ] ],
        [ "raspberrypi", "namespacecen_1_1hint_1_1raspberrypi.html", [
          [ "video_layer", "structcen_1_1hint_1_1raspberrypi_1_1video__layer.html", null ]
        ] ],
        [ "windows", "namespacecen_1_1hint_1_1windows.html", [
          [ "d3d_compiler", "structcen_1_1hint_1_1windows_1_1d3d__compiler.html", null ],
          [ "no_thread_naming", "structcen_1_1hint_1_1windows_1_1no__thread__naming.html", null ],
          [ "enable_message_loop", "structcen_1_1hint_1_1windows_1_1enable__message__loop.html", null ],
          [ "no_close_on_alt_f4", "structcen_1_1hint_1_1windows_1_1no__close__on__alt__f4.html", null ],
          [ "int_resource_icon", "structcen_1_1hint_1_1windows_1_1int__resource__icon.html", null ],
          [ "int_resource_icon_small", "structcen_1_1hint_1_1windows_1_1int__resource__icon__small.html", null ]
        ] ],
        [ "winrt", "namespacecen_1_1hint_1_1winrt.html", [
          [ "privacy_policy_label", "structcen_1_1hint_1_1winrt_1_1privacy__policy__label.html", null ],
          [ "privacy_policy_url", "structcen_1_1hint_1_1winrt_1_1privacy__policy__url.html", null ],
          [ "handle_back_button", "structcen_1_1hint_1_1winrt_1_1handle__back__button.html", null ]
        ] ],
        [ "x11", "namespacecen_1_1hint_1_1x11.html", [
          [ "net_wm_ping", "structcen_1_1hint_1_1x11_1_1net__wm__ping.html", null ],
          [ "net_wm_bypass_compositor", "structcen_1_1hint_1_1x11_1_1net__wm__bypass__compositor.html", null ],
          [ "xinerama", "structcen_1_1hint_1_1x11_1_1xinerama.html", null ],
          [ "xrandr", "structcen_1_1hint_1_1x11_1_1xrandr.html", null ],
          [ "xvidmode", "structcen_1_1hint_1_1x11_1_1xvidmode.html", null ],
          [ "force_egl", "structcen_1_1hint_1_1x11_1_1force__egl.html", null ],
          [ "window_visual_id", "structcen_1_1hint_1_1x11_1_1window__visual__id.html", null ]
        ] ],
        [ "xinput", "namespacecen_1_1hint_1_1xinput.html", [
          [ "is_enabled", "structcen_1_1hint_1_1xinput_1_1is__enabled.html", null ],
          [ "use_old_joystick_mapping", "structcen_1_1hint_1_1xinput_1_1use__old__joystick__mapping.html", null ]
        ] ],
        [ "render_driver", "structcen_1_1hint_1_1render__driver.html", null ],
        [ "audio_resampling_mode", "structcen_1_1hint_1_1audio__resampling__mode.html", null ],
        [ "audio_include_monitors", "structcen_1_1hint_1_1audio__include__monitors.html", null ],
        [ "audio_device_stream_role", "structcen_1_1hint_1_1audio__device__stream__role.html", null ],
        [ "scale_quality", "structcen_1_1hint_1_1scale__quality.html", null ],
        [ "framebuffer_acceleration", "structcen_1_1hint_1_1framebuffer__acceleration.html", null ],
        [ "audio_category", "structcen_1_1hint_1_1audio__category.html", null ],
        [ "wave_riff_chunk_size", "structcen_1_1hint_1_1wave__riff__chunk__size.html", null ],
        [ "wave_truncation", "structcen_1_1hint_1_1wave__truncation.html", null ],
        [ "wave_fact_chunk", "structcen_1_1hint_1_1wave__fact__chunk.html", null ],
        [ "logical_size_mode", "structcen_1_1hint_1_1logical__size__mode.html", null ],
        [ "accelerometer_as_joystick", "structcen_1_1hint_1_1accelerometer__as__joystick.html", null ],
        [ "allow_top_most", "structcen_1_1hint_1_1allow__top__most.html", null ],
        [ "bmp_save_legacy_format", "structcen_1_1hint_1_1bmp__save__legacy__format.html", null ],
        [ "double_buffer", "structcen_1_1hint_1_1double__buffer.html", null ],
        [ "enable_steam_controllers", "structcen_1_1hint_1_1enable__steam__controllers.html", null ],
        [ "grab_keyboard", "structcen_1_1hint_1_1grab__keyboard.html", null ],
        [ "idle_timer_disabled", "structcen_1_1hint_1_1idle__timer__disabled.html", null ],
        [ "ime_internal_editing", "structcen_1_1hint_1_1ime__internal__editing.html", null ],
        [ "no_signal_handlers", "structcen_1_1hint_1_1no__signal__handlers.html", null ],
        [ "opengl_es_driver", "structcen_1_1hint_1_1opengl__es__driver.html", null ],
        [ "enable_opengl_shaders", "structcen_1_1hint_1_1enable__opengl__shaders.html", null ],
        [ "vsync", "structcen_1_1hint_1_1vsync.html", null ],
        [ "allow_screensaver", "structcen_1_1hint_1_1allow__screensaver.html", null ],
        [ "video_external_context", "structcen_1_1hint_1_1video__external__context.html", null ],
        [ "disable_high_dpi", "structcen_1_1hint_1_1disable__high__dpi.html", null ],
        [ "minimize_on_focus_loss", "structcen_1_1hint_1_1minimize__on__focus__loss.html", null ],
        [ "window_frame_usable_while_cursor_hidden", "structcen_1_1hint_1_1window__frame__usable__while__cursor__hidden.html", null ],
        [ "render_batching", "structcen_1_1hint_1_1render__batching.html", null ],
        [ "return_key_hides_ime", "structcen_1_1hint_1_1return__key__hides__ime.html", null ],
        [ "touch_mouse_events", "structcen_1_1hint_1_1touch__mouse__events.html", null ],
        [ "mouse_touch_events", "structcen_1_1hint_1_1mouse__touch__events.html", null ],
        [ "tv_remote_as_joystick", "structcen_1_1hint_1_1tv__remote__as__joystick.html", null ],
        [ "display_usable_bounds", "structcen_1_1hint_1_1display__usable__bounds.html", null ],
        [ "orientations", "structcen_1_1hint_1_1orientations.html", null ],
        [ "window_share_pixel_format", "structcen_1_1hint_1_1window__share__pixel__format.html", null ],
        [ "event_logging", "structcen_1_1hint_1_1event__logging.html", null ],
        [ "thread_stack_size", "structcen_1_1hint_1_1thread__stack__size.html", null ],
        [ "timer_resolution", "structcen_1_1hint_1_1timer__resolution.html", null ],
        [ "preferred_locales", "structcen_1_1hint_1_1preferred__locales.html", null ],
        [ "thread_priority_policy", "structcen_1_1hint_1_1thread__priority__policy.html", null ],
        [ "treat_time_critical_as_real_time", "structcen_1_1hint_1_1treat__time__critical__as__real__time.html", null ],
        [ "audio_device_app_name", "structcen_1_1hint_1_1audio__device__app__name.html", null ],
        [ "audio_device_stream_name", "structcen_1_1hint_1_1audio__device__stream__name.html", null ],
        [ "enum_hint", "classcen_1_1hint_1_1enum__hint.html", "classcen_1_1hint_1_1enum__hint" ]
      ] ],
      [ "touch", "namespacecen_1_1touch.html", [
        [ "finger_state", "structcen_1_1touch_1_1finger__state.html", "structcen_1_1touch_1_1finger__state" ]
      ] ],
      [ "music", "classcen_1_1music.html", "classcen_1_1music" ],
      [ "basic_sound_effect", "classcen_1_1basic__sound__effect.html", "classcen_1_1basic__sound__effect" ],
      [ "cen_error", "classcen_1_1cen__error.html", "classcen_1_1cen__error" ],
      [ "sdl_error", "classcen_1_1sdl__error.html", "classcen_1_1sdl__error" ],
      [ "img_error", "classcen_1_1img__error.html", "classcen_1_1img__error" ],
      [ "ttf_error", "classcen_1_1ttf__error.html", "classcen_1_1ttf__error" ],
      [ "mix_error", "classcen_1_1mix__error.html", "classcen_1_1mix__error" ],
      [ "config", "structcen_1_1config.html", "structcen_1_1config" ],
      [ "library", "classcen_1_1library.html", "classcen_1_1library" ],
      [ "result", "classcen_1_1result.html", "classcen_1_1result" ],
      [ "sdl_string", "classcen_1_1sdl__string.html", "classcen_1_1sdl__string" ],
      [ "audio_device_event", "classcen_1_1audio__device__event.html", "classcen_1_1audio__device__event" ],
      [ "common_event", "classcen_1_1common__event.html", "classcen_1_1common__event" ],
      [ "controller_axis_event", "classcen_1_1controller__axis__event.html", "classcen_1_1controller__axis__event" ],
      [ "controller_button_event", "classcen_1_1controller__button__event.html", "classcen_1_1controller__button__event" ],
      [ "controller_device_event", "classcen_1_1controller__device__event.html", "classcen_1_1controller__device__event" ],
      [ "controller_sensor_event", "classcen_1_1controller__sensor__event.html", "classcen_1_1controller__sensor__event" ],
      [ "controller_touchpad_event", "classcen_1_1controller__touchpad__event.html", "classcen_1_1controller__touchpad__event" ],
      [ "display_event", "classcen_1_1display__event.html", "classcen_1_1display__event" ],
      [ "dollar_gesture_event", "classcen_1_1dollar__gesture__event.html", "classcen_1_1dollar__gesture__event" ],
      [ "drop_event", "classcen_1_1drop__event.html", "classcen_1_1drop__event" ],
      [ "event", "classcen_1_1event.html", "classcen_1_1event" ],
      [ "event_sink", "classcen_1_1event__sink.html", "classcen_1_1event__sink" ],
      [ "event_dispatcher", "classcen_1_1event__dispatcher.html", "classcen_1_1event__dispatcher" ],
      [ "joy_axis_event", "classcen_1_1joy__axis__event.html", "classcen_1_1joy__axis__event" ],
      [ "joy_ball_event", "classcen_1_1joy__ball__event.html", "classcen_1_1joy__ball__event" ],
      [ "joy_button_event", "classcen_1_1joy__button__event.html", "classcen_1_1joy__button__event" ],
      [ "joy_device_event", "classcen_1_1joy__device__event.html", "classcen_1_1joy__device__event" ],
      [ "joy_hat_event", "classcen_1_1joy__hat__event.html", "classcen_1_1joy__hat__event" ],
      [ "keyboard_event", "classcen_1_1keyboard__event.html", "classcen_1_1keyboard__event" ],
      [ "mouse_button_event", "classcen_1_1mouse__button__event.html", "classcen_1_1mouse__button__event" ],
      [ "mouse_motion_event", "classcen_1_1mouse__motion__event.html", "classcen_1_1mouse__motion__event" ],
      [ "mouse_wheel_event", "classcen_1_1mouse__wheel__event.html", "classcen_1_1mouse__wheel__event" ],
      [ "multi_gesture_event", "classcen_1_1multi__gesture__event.html", "classcen_1_1multi__gesture__event" ],
      [ "quit_event", "classcen_1_1quit__event.html", "classcen_1_1quit__event" ],
      [ "sensor_event", "classcen_1_1sensor__event.html", "classcen_1_1sensor__event" ],
      [ "text_editing_event", "classcen_1_1text__editing__event.html", "classcen_1_1text__editing__event" ],
      [ "text_input_event", "classcen_1_1text__input__event.html", "classcen_1_1text__input__event" ],
      [ "touch_finger_event", "classcen_1_1touch__finger__event.html", "classcen_1_1touch__finger__event" ],
      [ "user_event", "classcen_1_1user__event.html", "classcen_1_1user__event" ],
      [ "window_event", "classcen_1_1window__event.html", "classcen_1_1window__event" ],
      [ "file", "classcen_1_1file.html", "classcen_1_1file" ],
      [ "hint_callback", "classcen_1_1hint__callback.html", "classcen_1_1hint__callback" ],
      [ "basic_controller", "classcen_1_1basic__controller.html", "classcen_1_1basic__controller" ],
      [ "basic_haptic", "classcen_1_1basic__haptic.html", "classcen_1_1basic__haptic" ],
      [ "haptic_condition", "classcen_1_1haptic__condition.html", "classcen_1_1haptic__condition" ],
      [ "haptic_constant", "classcen_1_1haptic__constant.html", "classcen_1_1haptic__constant" ],
      [ "haptic_custom", "classcen_1_1haptic__custom.html", "classcen_1_1haptic__custom" ],
      [ "haptic_direction", "classcen_1_1haptic__direction.html", "classcen_1_1haptic__direction" ],
      [ "haptic_effect", "classcen_1_1haptic__effect.html", "classcen_1_1haptic__effect" ],
      [ "haptic_left_right", "classcen_1_1haptic__left__right.html", "classcen_1_1haptic__left__right" ],
      [ "haptic_periodic", "classcen_1_1haptic__periodic.html", "classcen_1_1haptic__periodic" ],
      [ "haptic_ramp", "classcen_1_1haptic__ramp.html", "classcen_1_1haptic__ramp" ],
      [ "ball_axis_change", "structcen_1_1ball__axis__change.html", "structcen_1_1ball__axis__change" ],
      [ "basic_joystick", "classcen_1_1basic__joystick.html", "classcen_1_1basic__joystick" ],
      [ "key_code", "classcen_1_1key__code.html", "classcen_1_1key__code" ],
      [ "keyboard", "classcen_1_1keyboard.html", "classcen_1_1keyboard" ],
      [ "mouse", "classcen_1_1mouse.html", "classcen_1_1mouse" ],
      [ "scan_code", "classcen_1_1scan__code.html", "classcen_1_1scan__code" ],
      [ "basic_sensor", "classcen_1_1basic__sensor.html", "classcen_1_1basic__sensor" ],
      [ "basic_area", "structcen_1_1basic__area.html", "structcen_1_1basic__area" ],
      [ "point_traits", "classcen_1_1point__traits.html", "classcen_1_1point__traits" ],
      [ "basic_point", "classcen_1_1basic__point.html", "classcen_1_1basic__point" ],
      [ "rect_traits", "classcen_1_1rect__traits.html", "classcen_1_1rect__traits" ],
      [ "basic_rect", "classcen_1_1basic__rect.html", "classcen_1_1basic__rect" ],
      [ "vector3", "structcen_1_1vector3.html", "structcen_1_1vector3" ],
      [ "simd_block", "classcen_1_1simd__block.html", "classcen_1_1simd__block" ],
      [ "locale", "classcen_1_1locale.html", "classcen_1_1locale" ],
      [ "shared_object", "classcen_1_1shared__object.html", "classcen_1_1shared__object" ],
      [ "condition", "classcen_1_1condition.html", "classcen_1_1condition" ],
      [ "mutex", "classcen_1_1mutex.html", "classcen_1_1mutex" ],
      [ "scoped_lock", "classcen_1_1scoped__lock.html", "classcen_1_1scoped__lock" ],
      [ "semaphore", "classcen_1_1semaphore.html", "classcen_1_1semaphore" ],
      [ "thread", "classcen_1_1thread.html", "classcen_1_1thread" ],
      [ "try_lock", "classcen_1_1try__lock.html", "classcen_1_1try__lock" ],
      [ "blend_task", "structcen_1_1blend__task.html", "structcen_1_1blend__task" ],
      [ "color", "classcen_1_1color.html", "classcen_1_1color" ],
      [ "basic_cursor", "classcen_1_1basic__cursor.html", "classcen_1_1basic__cursor" ],
      [ "glyph_metrics", "structcen_1_1glyph__metrics.html", "structcen_1_1glyph__metrics" ],
      [ "font", "classcen_1_1font.html", "classcen_1_1font" ],
      [ "font_cache", "classcen_1_1font__cache.html", "classcen_1_1font__cache" ],
      [ "message_box", "classcen_1_1message__box.html", "classcen_1_1message__box" ],
      [ "gl_library", "classcen_1_1gl__library.html", "classcen_1_1gl__library" ],
      [ "palette", "classcen_1_1palette.html", "classcen_1_1palette" ],
      [ "basic_pixel_format_info", "classcen_1_1basic__pixel__format__info.html", "classcen_1_1basic__pixel__format__info" ],
      [ "basic_renderer", "classcen_1_1basic__renderer.html", "classcen_1_1basic__renderer" ],
      [ "renderer_info", "classcen_1_1renderer__info.html", "classcen_1_1renderer__info" ],
      [ "dpi_info", "structcen_1_1dpi__info.html", "structcen_1_1dpi__info" ],
      [ "basic_surface", "classcen_1_1basic__surface.html", "classcen_1_1basic__surface" ],
      [ "basic_texture", "classcen_1_1basic__texture.html", "classcen_1_1basic__texture" ],
      [ "unicode_string", "classcen_1_1unicode__string.html", "classcen_1_1unicode__string" ],
      [ "vk_library", "classcen_1_1vk__library.html", "classcen_1_1vk__library" ],
      [ "basic_window", "classcen_1_1basic__window.html", "classcen_1_1basic__window" ]
    ] ],
    [ "version", "structversion.html", null ]
];